https://www.kaggle.com/datasets/arianazmoudeh/airbnbopendata/data

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Affiche toutes les lignes
pd.set_option("display.max_rows", None)

# Affiche toutes les colonnes
pd.set_option("display.max_columns", None)

pd.set_option("display.max_colwidth", 50)

In [28]:
df_path = "Airbnb_Open_Data.csv"

df = pd.read_csv(df_path, dtype={"license": str})

In [29]:
# Vue d'ensemble (shape, dtypes, duplicates)
def quick_overview(df, name):
    print(f"\n{name.upper()} SHAPE: {df.shape}")
    display(df.head(2))
    display(df.dtypes)
    display(df.describe(include="all").T)
    
quick_overview(df, "Dataset")

DATASET SHAPE: (102599, 26)

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,2020.0,$966,$193,10.0,9.0,10/19/2021,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0,5/21/2022,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN

id                                  int64
NAME                               object
host id                             int64
host_identity_verified             object
host name                          object
neighbourhood group                object
neighbourhood                      object
lat                               float64
long                              float64
country                            object
country code                       object
instant_bookable                   object
cancellation_policy                object
room type                          object
Construction year                 float64
price                              object
service fee                        object
minimum nights                    float64
number of reviews                 float64
last review                        object
reviews per month                 float64
review rate number                float64
calculated host listings count    float64
availability 365                  float64
house_rules                        object
license                            object
dtype: object

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
id,102599.0,NaN,NaN,NaN,29146234.52213,16257505.607309,1001254.0,15085814.5,29136603.0,43201198.0,57367417.0
NAME,102349,61281,Home away from home,33,NaN,NaN,NaN,NaN,NaN,NaN,NaN
host id,102599.0,NaN,NaN,NaN,49254111474.328667,28538996644.374878,123600518.0,24583328475.0,49117739352.0,73996495817.0,98763129024.0
host_identity_verified,102310,2,unconfirmed,51200,NaN,NaN,NaN,NaN,NaN,NaN,NaN
host name,102193,13190,Michael,881,NaN,NaN,NaN,NaN,NaN,NaN,NaN
neighbourhood group,102570,7,Manhattan,43792,NaN,NaN,NaN,NaN,NaN,NaN,NaN
neighbourhood,102583,224,Bedford-Stuyvesant,7937,NaN,NaN,NaN,NaN,NaN,NaN,NaN
lat,102591.0,NaN,NaN,NaN,40.728094,0.055857,40.49979,40.68874,40.72229,40.76276,40.91697
long,102591.0,NaN,NaN,NaN,-73.949644,0.049521,-74.24984,-73.98258,-73.95444,-73.93235,-73.70522
country,102067,1,United States,102067,NaN,NaN,NaN,NaN,NaN,NaN,NaN
country code,102468,1,US,102468,NaN,NaN,NaN,NaN,NaN,NaN,NaN
instant_bookable,102494,2,False,51474,NaN,NaN,NaN,NaN,NaN,NaN,NaN
cancellation_policy,102523,3,moderate,34343,NaN,NaN,NaN,NaN,NaN,NaN,NaN
room type,102599,4,Entire home/apt,53701,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Construction year,102385.0,NaN,NaN,NaN,2012.487464,5.765556,2003.0,2007.0,2012.0,2017.0,2022.0
price,102352,1151,$206,137,NaN,NaN,NaN,NaN,NaN,NaN,NaN
service fee,102326,231,$41,526,NaN,NaN,NaN,NaN,NaN,NaN,NaN
minimum nights,102190.0,NaN,NaN,NaN,8.135845,30.553781,-1223.0,2.0,3.0,5.0,5645.0
number of reviews,102416.0,NaN,NaN,NaN,27.483743,49.508954,0.0,1.0,7.0,30.0,1024.0
last review,86706,2477,6/23/2019,2443,NaN,NaN,NaN,NaN,NaN,NaN,NaN
reviews per month,86720.0,NaN,NaN,NaN,1.374022,1.746621,0.01,0.22,0.74,2.0,90.0
review rate number,102273.0,NaN,NaN,NaN,3.279106,1.284657,1.0,2.0,3.0,4.0,5.0
calculated host listings count,102280.0,NaN,NaN,NaN,7.936605,32.21878,1.0,1.0,1.0,2.0,332.0
availability 365,102151.0,NaN,NaN,NaN,141.133254,135.435024,-10.0,3.0,96.0,269.0,3677.0
house_rules,50468,1976,#NAME?,2712,NaN,NaN,NaN,NaN,NaN,NaN,NaN
license,2,1,41662/AL,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### **Type de données**
#### **Identification propriétaire :**
- host_id
- host_name
- host_identity_verified
- calculated_host_listings_count
#### **Identification logement :**
- id
- name
- room_type
- construction_year
- house_rules
- license
#### **Localisation logement :**
- neighbourhood_group
- neighbourhood
- latitude
- longitude
- country
- country_code
#### **Possibilités de réservation :**
- instant_bookable
- cancellation_policy
- minimum_nights
- availability_365
- price
- service_fee
#### **Notes du logement :**
- number_of_reviews
- last_review
- reviews_per_month
- review_rate_number

In [30]:
df = df.rename(columns={
    'id': 'id',
    'NAME': 'name',
    'host id': 'host_id',
    'host_identity_verified': 'host_identity_verified',
    'host name': 'host_name',
    'neighbourhood group': 'neighbourhood_group',
    'neighbourhood': 'neighbourhood',
    'lat': 'latitude',
    'long': 'longitude',
    'country': 'country',
    'country code': 'country_code',
    'instant_bookable': 'instant_bookable',
    'cancellation_policy': 'cancellation_policy',
    'room type': 'room_type',
    'Construction year': 'construction_year',
    'price': 'price',
    'service fee': 'service_fee',
    'minimum nights': 'minimum_nights',
    'number of reviews': 'number_of_reviews',
    'last review': 'last_review',
    'reviews per month': 'reviews_per_month',
    'review rate number': 'review_rate_number',
    'calculated host listings count': 'calculated_host_listings_count',
    'availability 365': 'availability_365',
    'house_rules': 'house_rules',
    'license': 'license'
})

In [31]:
df.columns

Index(['id', 'name', 'host_id', 'host_identity_verified', 'host_name',
       'neighbourhood_group', 'neighbourhood', 'latitude', 'longitude',
       'country', 'country_code', 'instant_bookable', 'cancellation_policy',
       'room_type', 'construction_year', 'price', 'service_fee',
       'minimum_nights', 'number_of_reviews', 'last_review',
       'reviews_per_month', 'review_rate_number',
       'calculated_host_listings_count', 'availability_365', 'house_rules',
       'license'],
      dtype='object')

In [32]:
df.isna().sum()

id                                     0
name                                 250
host_id                                0
host_identity_verified               289
host_name                            406
neighbourhood_group                   29
neighbourhood                         16
latitude                               8
longitude                              8
country                              532
country_code                         131
instant_bookable                     105
cancellation_policy                   76
room_type                              0
construction_year                    214
price                                247
service_fee                          273
minimum_nights                       409
number_of_reviews                    183
last_review                        15893
reviews_per_month                  15879
review_rate_number                   326
calculated_host_listings_count       319
availability_365                     448
house_rules                        52131
license                           102597
dtype: int64

In [33]:
#df["host_id"].value_counts()